# Generated by Django 5.2.5 on 2025-08-21 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('Description', models.TextField(blank=True)),
                ('InitialBid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Image', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, choices=[('Fash', 'Fashion'), ('Toys', 'Toys'), ('Elec', 'Electronics'), ('Home', 'Home')], default=None, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('Winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Comenting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting', to=settings.AUTH_USER_MODEL)),
                ('OnListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingComment', to='auctions.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to=settings.AUTH_USER_MODEL)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listingBid', to='auctions.listing')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Watchlist',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='auctions.listing'),
        ),
    ]
