# Generated by Django 5.2.5 on 2025-08-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_category_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='InitialBid',
            new_name='CurrentBid',
        ),
    ]
