# Generated by Django 4.2.23 on 2025-08-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(blank=True, choices=[('Fash', 'Fashion'), ('Toys', 'Toys'), ('Elec', 'Electronics'), ('Home', 'Home')], default=None, max_length=100, null=True),
        ),
    ]
